### ISSUE TITLE
Error Dialog

### ISSUE THREAD

**Issue by HusseinMosaad** [hikalkan/jtable#1607]
Hi Dear,

Thank you for that awesome plugin, i have an issue and i can not resolve.
Every time i select data to show in jtable it still show the dialog and says error and there is no any error in the console and the List function is called and i tested the returned josn object and everything is ok. But i don't know why it gives me that error dialog with only Error message

I'm using asp.net mvc 5

Thanks
![untitled](https://cloud.githubusercontent.com/assets/6317847/5600597/f5aee24c-92e5-11e4-95d2-ad10197006c0.png)

**Comment by moezkorkmaz** [comment]
Hi!

I got this error because my json was not formatted properly.
Please check if the field names start with capital letters and are set in quotes. I had to write a wrapper which creates a compatible json though (in Java). I guess ASP (the base the developer uses) produces some IMHO weird json and the dev relies on this.

Greets,
Murat

**Comment by HusseinMosaad** [comment]
Hi Murat,

You are right, the josn that jtable received is in camelCase mode and i
make it to be in PascalCase mode and it works and jtable displays data
perfectly, but when i try to create a new record jtable post a json with
record root element so it can't be deserialized to match my model.

I don't know how to fix it with better way.
Thanks

**Comment by HusseinMosaad** [comment]
Hi Murat,

Thank you very much for your help.
I have fixed the problem and jtable is working perfect now.

Thanks,
Hussein Mosaad
